"use client";
import Image from "next/image";
import { FormEvent, useState } from "react";

const number = "918886448989";
const wa = (plan = "the available internet plans") => `https://wa.me/${number}?text=${encodeURIComponent(`Hello CVN Fiber Net, I would like to check internet availability in my area. I am interested in ${plan}.`)}`;

const plans = [
  { no:"01", hint:"Plans start here", name:"Starter Fiber", price:"399", list:["Unlimited data","High-speed fiber connection","HD streaming","Work-from-home ready"] },
  { no:"02", hint:"40 Mbps", name:"Entertainment Plan", price:"449", badge:"★ Best for Entertainment", list:["Unlimited internet","Wi-Fi + OTT pack","12+ OTT platforms"] },
  { no:"03", hint:"75 Mbps", name:"Superfast Plan", price:"575", list:["Unlimited internet","Stable low-latency connection","Ideal for streaming and gaming"], package:"6-month package: ₹3,300" },
];

export default function Home(){
  const [menu,setMenu]=useState(false);
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const msg=`Hello CVN Fiber Net, I want to check availability. Name: ${d.get("name")}, Mobile: ${d.get("mobile")}, Area: ${d.get("area")}, Pincode: ${d.get("pincode")}, Plan: ${d.get("plan")}, Message: ${d.get("message")||"None"}`;window.open(`https://wa.me/${number}?text=${encodeURIComponent(msg)}`,"_blank")}
  return <main>
    <header className="header"><a className="brand" href="#home"><Image src="/cvn-logo.jpg" alt="CVN Fiber Net Service logo" width={52} height={52}/><span><b>CVN</b> Fiber Net<small>Apne Area Ka Apna Wi-Fi</small></span></a><button className="menuBtn" onClick={()=>setMenu(!menu)} aria-label="Open navigation">☰</button><nav className={menu?"open":""} onClick={()=>setMenu(false)}><a href="#home">Home</a><a href="#plans">Plans</a><a href="#benefits">Benefits</a><a href="#coverage">Coverage</a><a href="#ott">OTT</a><a href="#contact">Contact</a></nav><a className="button small desktopCta" href="#coverage">Check Availability</a></header>
    <section className="hero" id="home"><div className="heroGlow"/><div className="heroCopy"><div className="eyebrow"><span/> FAST • STABLE • AFFORDABLE</div><h1>Ultra-Fast Fiber<br/>Internet for <em>Your Home</em></h1><p>Enjoy unlimited data, smooth streaming, lag-free gaming, reliable video calls, and fast downloads with CVN Fiber Net.</p><div className="starting"><b>₹399</b><span>Plans starting at<br/><strong>per month</strong></span></div><div className="heroPoints"><span>✓ Unlimited data</span><span>✓ Stable fiber connection</span><span>✓ Local customer support</span></div><div className="actions"><a className="button" href="#coverage">Check Availability →</a><a className="button ghost" href={wa()}>WhatsApp Us</a><a className="textLink" href="tel:+918886448989">Call Now ↗</a></div></div><div className="heroVisual"><div className="signal"><i/><i/><i/></div><div className="router"><span className="antenna a1"/><span className="antenna a2"/><div className="routerFace"><b>CVN</b><small>FIBER</small><div className="lights">• • • •</div></div></div><div className="speedCard"><small>CONNECTED</small><b>FIBER</b><span>Stable connection</span></div><div className="city">HYDERABAD • TADBUN</div></div></section>
    <section className="trust"><div><i>∞</i><span>Unlimited Data</span></div><div><i>↯</i><span>High-Speed Fiber</span></div><div><i>◉</i><span>Stable Connection</span></div><div><i>▶</i><span>Smooth Streaming</span></div><div><i>♥</i><span>Local Support</span></div></section>
    <section className="section" id="plans"><div className="sectionHead"><div><span className="kicker">CHOOSE YOUR SPEED</span><h2>Simple plans. Serious speed.</h2></div><p>Unlimited fiber internet for the way your home connects—without confusing claims.</p></div><div className="planGrid">{plans.map(p=><article className={`plan ${p.badge?"featured":""}`} key={p.no}>{p.badge&&<div className="badge">{p.badge}</div>}<div className="planTop"><span>{p.no}</span><p>{p.hint}</p></div><h3>{p.name}</h3><div className="price"><b>₹{p.price}</b><span>/ month</span></div><ul>{p.list.map(x=><li key={x}>✓ {x}</li>)}</ul>{p.package&&<p className="package">{p.package}</p>}<div className="planActions"><a className="button" href="#coverage">Choose Plan</a><a href={wa(`the ${p.name}`)}>WhatsApp to Book ↗</a><a href="#coverage">Check Availability</a></div></article>)}</div><p className="fineprint">Free installation is advertised on eligible 6 & 12 month packages. Confirm availability and terms with CVN.</p></section>
    <section className="section ott" id="ott"><div className="ottIntro"><span className="kicker">INTERNET + ENTERTAINMENT</span><h2>More than Wi-Fi.<br/>Your entertainment hub.</h2><p>The 40 Mbps Entertainment Plan combines unlimited internet with an OTT pack at ₹449 per month.</p><p className="fineprint">OTT platform availability may vary. Contact CVN for the current app list.</p></div><div className="ottGrid"><article><span>▶</span><h3>12+ OTT platforms</h3><p>Movies, regional entertainment, sports, devotional content and more.</p></article><article><span>▣</span><h3>Multiple screens</h3><p>Watch on mobile, TV, laptop and supported devices.</p></article><article><span>∞</span><h3>Unlimited internet</h3><p>One affordable pack for internet and entertainment.</p></article></div></section>
    <section className="section switch"><div className="problem"><span className="kicker red">STILL BUFFERING?</span><h2>Slow internet<br/>breaks the moment.</h2><p>◌ <span>Buffering & slow downloads</span></p><p>⌁ <span>Dropped video calls</span></p><p>◔ <span>Unstable gaming</span></p></div><div className="dividerArrow">→</div><div className="solution"><span className="kicker">SWITCH TO CVN</span><h2>Speed that keeps<br/>your home moving.</h2><p>✓ <span>Stable fiber connection</span></p><p>✓ <span>Smooth streaming & gaming</span></p><p>✓ <span>Support from your local team</span></p><a className="button" href="#coverage">Check your area →</a></div></section>
    <section className="section" id="benefits"><div className="sectionHead"><div><span className="kicker">WHY CVN FIBER NET?</span><h2>Built around your everyday.</h2></div></div><div className="whyGrid">{[["01","↯","High-Speed Fiber"],["02","∞","Unlimited Data"],["03","▶","Streaming Ready"],["04","⌁","Gaming Ready"],["05","▣","Work From Home"],["06","⌘","Multiple-Device Support"]].map(x=><article key={x[0]}><b>{x[0]}</b><i>{x[1]}</i><h3>{x[2]}</h3></article>)}</div></section>
    <section className="coverage section" id="coverage"><div className="coverageCopy"><span className="kicker">LOCAL FIBER. LOCAL SUPPORT.</span><h2>Is CVN Fiber Net<br/>Available in Your Area?</h2><p>Share your location and preferred plan. Your completed enquiry will open in WhatsApp, ready to send to our local team.</p><div className="areas"><b>Service areas mentioned:</b><span>Ali Bagh Road, Tadban, Hyderabad</span><span>Tadban X Road</span><span>Kalapathar and nearby service areas</span></div></div><form onSubmit={submit}><div className="formTitle"><span>CHECK COVERAGE</span><b>Usually takes under a minute</b></div><label>Full name<input name="name" placeholder="Enter your name" required/></label><label>Mobile number<input name="mobile" inputMode="numeric" pattern="[0-9]{10}" placeholder="10-digit mobile number" required/></label><div className="two"><label>Area / locality<input name="area" placeholder="e.g. Tadban" required/></label><label>Pincode<input name="pincode" inputMode="numeric" pattern="[0-9]{6}" placeholder="6 digits" required/></label></div><label>Preferred plan<select name="plan" required defaultValue=""><option value="" disabled>Select a plan</option>{plans.map(p=><option key={p.no}>{p.name}</option>)}</select></label><label>Optional message<textarea name="message" placeholder="Landmark or any question" rows={3}/></label><button className="button submit">Check Availability →</button><small>By continuing, you agree to be contacted about your enquiry. Terms may apply.</small></form></section>
    <section className="section useCases"><span className="kicker">ONE CONNECTION. EVERYDAY POSSIBILITIES.</span><h2>Made for every kind of home</h2><div>{[["⌂","Families","Streaming, learning and sharing across devices."],["✎","Students","Classes, research and fast downloads."],["▣","Work from Home","Reliable calls and dependable daily work."],["⌁","Gamers","Stable, low-latency entertainment."],["▶","Movie & OTT Lovers","More entertainment in selected packs."]].map(x=><article key={x[1]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
    <section className="finalCta"><span className="kicker">YOUR LOCAL FIBER NETWORK</span><h2>Ready to Upgrade<br/>Your Internet?</h2><p>Book your CVN Fiber Net connection today and enjoy fast, stable, and affordable fiber internet.</p><div className="actions"><a className="button whatsapp" href={wa()}>WhatsApp: 888 644 89 89</a><a className="button ghost" href="tel:+918886448989">Call: 888 644 89 89</a><a className="textLink" href="tel:+918096448989">Alternate: 809 644 89 89</a></div></section>
    <footer id="contact"><div className="footerTop"><div><a className="brand footerBrand" href="#home"><Image src="/cvn-logo-3d.jpeg" alt="CVN Fiber Net Service" width={52} height={52}/><span><b>CVN</b> Fiber Net<small>Broadband Service</small></span></a><p>Apne Area Ka Apna Wi-Fi</p><p>Fast • Stable • Affordable</p></div><div><h3>Explore</h3><a href="#plans">Plans</a><a href="#coverage">Coverage</a><a href="#contact">Contact</a></div><div><h3>Contact</h3><a href="tel:+918886448989">888 644 89 89</a><a href="tel:+918096448989">809 644 89 89</a><p>Ali Bagh Road, Tadban,<br/>Hyderabad, Telangana</p></div><div><h3>Service hours</h3><p>Sat–Thu: 11:30 AM–9:30 PM</p><p>Friday: 3:30 PM–9:30 PM</p></div></div><div className="footerBottom"><span>© 2026 CVN Fiber Net Service. All rights reserved.</span><span>Privacy Policy · Terms</span></div></footer>
    <a className="floatingWa" href={wa()} aria-label="Enquire on WhatsApp">WA</a><div className="mobileBar"><a href={wa()}>WhatsApp</a><a href="tel:+918886448989">Call Now</a><a href="#coverage">Check Availability</a></div>
  </main>
}
