"use client";
import Image from "next/image";
import { FormEvent, useState } from "react";

const number = "918886448989";
const wa = (plan = "the available internet plans") => `https://wa.me/${number}?text=${encodeURIComponent(`Hello CVN Fiber Net, I would like to check internet availability in my area. I am interested in ${plan}.`)}`;

const plans = [
  { no: "01", hint: "Plans start here", name: "Starter Fiber", price: "399", list: ["Unlimited data", "High-speed fiber connection", "HD streaming", "Work-from-home ready"] },
  { no: "02", hint: "40 Mbps", name: "Entertainment Plan", price: "449", badge: "★ Best for Entertainment", list: ["Unlimited internet", "Wi-Fi + OTT pack", "12+ OTT platforms"] },
  { no: "03", hint: "75 Mbps", name: "Superfast Plan", price: "575", list: ["Unlimited internet", "Stable low-latency connection", "Ideal for streaming and gaming"], package: "6-month package: ₹3,300" },
];

const serviceAreas = [
  "Ali Bagh", "Kalapathar", "New Road", "Jahanuma", "Modern Town Colony",
  "Sattar Bagh", "Phool Bagh", "Chune Ki Bhatti", "Misri Gunj",
  "Chandulal Baradari", "Tadbun", "Zoo Park", "Mochi Colony",
  "Khaja Pahadi", "Eidgah Tadbun", "B.N.K. Colony", "Nizam Colony",
  "Makkah Colony", "Ranjan Colony", "Tekri",
];

const monthlyPlans = [
  ["40 Mbps", "CVN Connect", "₹399"], ["50 Mbps", "CVN Stream", "₹525"],
  ["75 Mbps", "CVN Family", "₹575"], ["100 Mbps", "CVN Entertainment", "₹649"],
  ["150 Mbps", "CVN Gamer", "₹775"], ["200 Mbps", "CVN Ultra", "₹949"],
  ["300 Mbps", "CVN Power", "₹1,199"], ["500 Mbps", "CVN Pro", "Contact for price"],
  ["1 Gbps", "CVN Ultimate", "Contact for price"],
];

const packagePlans = [
  ["40 Mbps", "CVN Connect", "₹2,500", "₹5,000"], ["50 Mbps", "CVN Stream", "₹3,000", "₹6,000"],
  ["75 Mbps", "CVN Family", "₹3,500", "₹7,000"], ["100 Mbps", "CVN Entertainment", "₹3,999", "₹7,999"],
  ["150 Mbps", "CVN Gamer", "₹5,499", "₹10,999"], ["200 Mbps", "CVN Ultra", "₹5,999", "₹11,999"],
  ["300 Mbps", "CVN Power", "₹6,666", "₹13,500"],
];

function PlanCatalogue(){return <section className="section catalogue" id="all-plans"><div className="sectionHead"><div><span className="kicker">COMPLETE PLAN CATALOGUE</span><h2>Every speed. One clear view.</h2></div><p>Compare monthly rentals and longer packages side by side. All listed plans include unlimited data under the applicable fair usage policy.</p></div><div className="tableLabel"><span>MONTHLY PLANS</span><b>Starting at ₹399/month</b></div><div className="planTable" role="table" aria-label="Monthly internet plans"><div className="planRow tableHead" role="row"><span>Speed</span><span>Package</span><span>Data</span><span>Monthly rental</span><span>Enquire</span></div>{monthlyPlans.map(p=><div className="planRow" role="row" key={p[0]}><strong>{p[0]}</strong><b>{p[1]}</b><span>Unlimited</span><strong className="gold">{p[2]}</strong><a href={wa(`the ${p[1]} plan`)}>WhatsApp ↗</a></div>)}</div><div className="packageHead"><div><span className="kicker">SAVE WITH LONGER PACKAGES</span><h3>6 &amp; 12 month packages</h3></div><div className="offerPill">12 months + 2 months extra free</div></div><div className="planTable" role="table" aria-label="Six and twelve month packages"><div className="planRow tableHead" role="row"><span>Speed</span><span>Package</span><span>6 months</span><span>12 months</span><span>Enquire</span></div>{packagePlans.map(p=><div className="planRow" role="row" key={p[0]}><strong>{p[0]}</strong><b>{p[1]}</b><strong className="gold">{p[2]}</strong><strong className="gold">{p[3]}</strong><a href={wa(`the ${p[1]} package`)}>WhatsApp ↗</a></div>)}</div><div className="planOffers"><article><b>1 month package</b><strong>₹499</strong><span>Connection charges</span></article><article><b>6 month package</b><strong>FREE</strong><span>Connection installation</span></article><article><b>12 month package</b><strong>FREE</strong><span>Installation + 2 months extra</span></article><article><b>OTT pack</b><strong>₹175</strong><span>Starting monthly price</span></article></div><p className="fineprint">Plan details are based on the supplied CVN tariff information. Availability, fair usage policy and package terms may apply.</p></section>}

export default function Home() {
  const [menu, setMenu] = useState(false);
  function toggleTheme() { const current = document.documentElement.dataset.theme || "dark"; const next = current === "dark" ? "light" : "dark"; document.documentElement.dataset.theme = next; localStorage.setItem("cvn-theme", next) }
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); const msg = `Hello CVN Fiber Net, I want to check availability. Name: ${d.get("name")}, Mobile: ${d.get("mobile")}, Area: ${d.get("area")}, Pincode: ${d.get("pincode")}, Plan: ${d.get("plan")}, Message: ${d.get("message") || "None"}`; window.open(`https://wa.me/${number}?text=${encodeURIComponent(msg)}`, "_blank") }
  return <main>
    <header className="header"><a className="brand" href="#home"><Image src="/cvn.jpeg" alt="CVN Fiber Net Service logo" width={52} height={52} /><span><b>CVN</b> Fiber Net<small>Apne Area Ka Apna Wi-Fi</small></span></a><button className="menuBtn" onClick={() => setMenu(!menu)} aria-label="Open navigation">☰</button><nav className={menu ? "open" : ""} onClick={() => setMenu(false)}><a href="#home">Home</a><a href="#plans">Plans</a><a href="#benefits">Benefits</a><a href="#coverage">Coverage</a><a href="#ott">OTT</a><a href="#contact">Contact</a></nav><button className="themeToggle" onClick={toggleTheme} aria-label="Toggle light and dark theme" title="Toggle color theme"><span className="sun">☀</span><span className="moon">☾</span></button><a className="button small desktopCta" href="#coverage">Check Availability</a></header>
    <section className="hero" id="home"><div className="heroGlow" /><div className="heroCopy"><div className="eyebrow"><span /> FAST • STABLE • AFFORDABLE</div><h1>Ultra-Fast Fiber<br />Internet for <em>Your Home</em></h1><p>Enjoy unlimited data, smooth streaming, lag-free gaming, reliable video calls, and fast downloads with CVN Fiber Net.</p><div className="starting"><b>₹399</b><span>Plans starting at<br /><strong>per month</strong></span></div><div className="heroPoints"><span>✓ Unlimited data</span><span>✓ Stable fiber connection</span><span>✓ Local customer support</span></div><div className="actions"><a className="button" href="#coverage">Check Availability →</a><a className="button ghost" href={wa()}>WhatsApp Us</a><a className="textLink" href="tel:+918886448989">Call Now ↗</a></div></div><div className="heroVisual"><div className="signal"><i /><i /><i /></div><div className="router"><span className="antenna a1" /><span className="antenna a2" /><div className="routerFace"><b>CVN</b><small>FIBER</small><div className="lights">• • • •</div></div></div><div className="speedCard"><small>CONNECTED</small><b>FIBER</b><span>Stable connection</span></div><div className="city">HYDERABAD • TADBUN</div></div></section>
    <section className="trust"><div><i>∞</i><span>Unlimited Data</span></div><div><i>↯</i><span>High-Speed Fiber</span></div><div><i>◉</i><span>Stable Connection</span></div><div><i>▶</i><span>Smooth Streaming</span></div><div><i>♥</i><span>Local Support</span></div></section>
    <section className="section" id="plans"><div className="sectionHead"><div><span className="kicker">CHOOSE YOUR SPEED</span><h2>Simple plans. Serious speed.</h2></div><p>Unlimited fiber internet for the way your home connects—without confusing claims.</p></div><div className="planGrid">{plans.map(p => <article className={`plan ${p.badge ? "featured" : ""}`} key={p.no}>{p.badge && <div className="badge">{p.badge}</div>}<div className="planTop"><span>{p.no}</span><p>{p.hint}</p></div><h3>{p.name}</h3><div className="price"><b>₹{p.price}</b><span>/ month</span></div><ul>{p.list.map(x => <li key={x}>✓ {x}</li>)}</ul>{p.package && <p className="package">{p.package}</p>}<div className="planActions"><a className="button" href="#coverage">Choose Plan</a><a href={wa(`the ${p.name}`)}>WhatsApp to Book ↗</a><a href="#coverage">Check Availability</a></div></article>)}</div><p className="fineprint">Free installation is advertised on eligible 6 & 12 month packages. Confirm availability and terms with CVN.</p></section>
    <section className="section ott" id="ott"><div className="ottIntro"><span className="kicker">MORE THAN INTERNET</span><h2>Internet + Entertainment<br />in One Affordable Pack</h2><p>Bring movies, series, regional shows, sports and devotional content together with selected CVN Fiber Net plans.</p><p className="fineprint">OTT availability may depend on the selected plan.</p></div><div className="ottGrid"><article><span>◈</span><h3>Movies &amp; Web Series</h3><p>JioHotstar · Hungama · Shemaroo · Watcho · Teleflicks OTT · Ultra</p></article><article><span>◈</span><h3>Regional Entertainment</h3><p>Tarang Plus · Raj TV · Aha · Stage · Jhakaas</p></article><article><span>◈</span><h3>Sports</h3><p>FanCode</p></article><article><span>◈</span><h3>Devotional Content</h3><p>Sanskar</p></article><article><span>◈</span><h3>Short-Form Entertainment</h3><p>Chana Jor</p></article></div></section>
    <section className="section switch"><div className="problem"><span className="kicker red">THE OLD EXPERIENCE</span><h2>Still struggling with<br />slow internet?</h2><p>× <span>Buffering</span></p><p>× <span>Video-call drops</span></p><p>× <span>Slow downloads</span></p><p>× <span>Unstable gaming</span></p></div><div className="dividerArrow">→</div><div className="solution"><span className="kicker">THE CVN EXPERIENCE</span><h2>Switch to CVN Fiber Net</h2><p>✓ <span>Fast FTTH connection</span></p><p>✓ <span>Unlimited data</span></p><p>✓ <span>Smooth video calls</span></p><p>✓ <span>Lag-free entertainment</span></p><p>✓ <span>Support from a local provider</span></p><a className="button" href="#coverage">Make the Switch →</a></div></section>
    <section className="section" id="benefits"><div className="sectionHead"><div><span className="kicker">BUILT FOR REAL LIFE</span><h2>Why homes choose CVN</h2></div><p>Connect mobiles, TVs, laptops and other devices with a dependable fiber connection.</p></div><div className="whyGrid">{[["01", "↯", "High-Speed Internet"], ["02", "∞", "Unlimited Data"], ["03", "◉", "Stable Connection"], ["04", "▶", "Smooth Streaming"], ["05", "⌁", "Gaming Ready"], ["06", "⌘", "Multiple-Device Support"]].map(x => <article key={x[0]}><b>{x[0]}</b><i>{x[1]}</i><h3>{x[2]}</h3></article>)}</div></section>
    <section className="coverage section" id="coverage"><div className="coverageCopy"><span className="kicker">LOCAL FIBER. LOCAL SUPPORT.</span><h2>Is CVN Fiber Net<br />Available in Your Area?</h2><p>We serve neighbourhoods across the Tadbun and Kalapathar area. Share your exact location and preferred plan for a quick availability check.</p><div className="areas"><b>Current service areas</b><p>Coverage can vary by street. Send your nearest landmark to confirm availability.</p><div className="areaChips">{serviceAreas.map(area => <span key={area}>{area}</span>)}</div></div></div><form onSubmit={submit}><div className="formTitle"><span>CHECK COVERAGE</span><b>Usually takes under a minute</b></div><label>Full name<input name="name" autoComplete="name" placeholder="Enter your name" required /></label><label>Mobile number<input name="mobile" autoComplete="tel" inputMode="numeric" pattern="[0-9]{10}" placeholder="10-digit mobile number" required /></label><div className="two"><label>Area / locality<input name="area" placeholder="e.g. Tadbun" required /></label><label>Pincode<input name="pincode" autoComplete="postal-code" inputMode="numeric" pattern="[0-9]{6}" placeholder="6 digits" required /></label></div><label>Preferred plan<select name="plan" required defaultValue=""><option value="" disabled>Select a plan</option>{monthlyPlans.map(p => <option key={p[1]}>{p[1]}</option>)}</select></label><label>Optional message<textarea name="message" placeholder="Nearest landmark or any question" rows={3} /></label><button className="button submit">Check Availability →</button><small>By continuing, you agree to be contacted about your enquiry. Terms may apply.</small></form></section>
    <section className="section useCases"><span className="kicker">ONE CONNECTION. EVERYDAY POSSIBILITIES.</span><h2>Made for every kind of home</h2><div>{[["⌂", "Families", "Streaming, learning and sharing across devices."], ["✎", "Students", "Classes, research and fast downloads."], ["▣", "Work from Home", "Reliable calls and dependable daily work."], ["⌁", "Gamers", "Stable, low-latency entertainment."], ["▶", "Movie & OTT Lovers", "More entertainment in selected packs."]].map(x => <article key={x[1]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
    <PlanCatalogue />
    <section className="finalCta"><span className="kicker">YOUR LOCAL FIBER NETWORK</span><h2>Ready to Upgrade<br />Your Internet?</h2><p>Book your CVN Fiber Net connection today and enjoy fast, stable, and affordable fiber internet.</p><div className="actions"><a className="button whatsapp" href={wa()}>WhatsApp: 888 644 89 89</a><a className="button ghost" href="tel:+918886448989">Call: 888 644 89 89</a><a className="textLink" href="tel:+918096448989">Office: 809 644 89 89</a></div></section>
    <footer id="contact"><div className="footerTop"><div><a className="brand footerBrand" href="#home"><Image src="/cvn.jpeg" alt="CVN Fiber Net Service" width={52} height={52} /><span><b>CVN</b> Fiber Net<small>Broadband Service</small></span></a><p>Apne Area Ka Apna Wi-Fi</p><p>Fast • Stable • Affordable</p></div><div><h3>Explore</h3><a href="#plans">Featured plans</a><a href="#all-plans">All plans</a><a href="#coverage">Coverage</a><a href="#contact">Contact</a></div><div><h3>Office numbers</h3><a href="tel:+918886448989">888 644 89 89</a><a href="tel:+918096448989">809 644 89 89</a><p>Ali Bagh New Road,<br />Hyderabad, Telangana</p></div><div><h3>Service hours</h3><p>Sat–Thu: 11:30 AM–9:30 PM</p><p>Friday: 3:30 PM–9:30 PM</p></div></div><div className="footerBottom"><span>© 2026 CVN Fiber Net Service. All rights reserved.</span><span>Privacy Policy · Terms</span></div></footer>
    <a className="floatingWa" href={wa()} aria-label="Enquire on WhatsApp" title="Chat on WhatsApp"><svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M16 3A13 13 0 0 0 5 22.8L3.3 29l6.4-1.7A13 13 0 1 0 16 3Zm0 23.6c-2.1 0-4.1-.6-5.9-1.6l-.4-.3-3.8 1 1-3.7-.3-.4A10.6 10.6 0 1 1 16 26.6Zm5.8-8c-.3-.2-1.9-.9-2.2-1-.3-.1-.5-.2-.7.1l-1 1.3c-.2.2-.4.2-.7 0a8.7 8.7 0 0 1-2.6-1.5 9.7 9.7 0 0 1-1.8-2.2c-.2-.3 0-.5.2-.7l.5-.5.3-.5c.1-.2.1-.4 0-.6l-1-2.3c-.3-.6-.6-.5-.8-.5h-.6c-.2 0-.6.1-.9.4-.3.3-1.1 1.1-1.1 2.6 0 1.6 1.2 3.1 1.3 3.3.2.2 2.3 3.4 5.4 4.8l1.8.7c.8.2 1.5.2 2 .1.6-.1 1.9-.8 2.2-1.5.3-.8.3-1.4.2-1.6-.1-.1-.3-.2-.6-.4Z" /></svg></a><div className="mobileBar"><a href={wa()}>WhatsApp</a><a href="tel:+918886448989">Call Now</a><a href="#coverage">Check Availability</a></div>
  </main>
}
